// <auto-generated />
using System;
using Akla.SharedData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Akla.SharedData.Migrations
{
    [DbContext(typeof(AklaDbContext))]
    [Migration("20250822224829_CreatedTheDbSetsAndTheRelationships")]
    partial class CreatedTheDbSetsAndTheRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Akla.SharedData.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Customer_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Customer_Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Join_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Akla.SharedData.Models.CustomerPhone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Customer_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Customer_Id");

                    b.ToTable("CustomerPhones");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Delivery_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dispath_Time")
                        .HasColumnType("datetime2");

                    b.Property<long>("Driver_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Order_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Driver_Id");

                    b.HasIndex("Order_Id")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("License_Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vehicle_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("License_Plate")
                        .IsUnique();

                    b.HasIndex("PrimaryPhoneNumber")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Akla.SharedData.Models.DriverPhone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Driver_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Driver_Id");

                    b.ToTable("DriverPhones");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("MenuItem_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Promotion_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MenuItem_Id");

                    b.HasIndex("Promotion_Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuCategoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MenuCategory_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("MenuItem_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategory_Id");

                    b.HasIndex("MenuItem_Id");

                    b.ToTable("MenuCategoryItems");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Preparation_Time")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuItemPromotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MenuItem_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Promotion_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MenuItem_Id");

                    b.HasIndex("Promotion_Id");

                    b.ToTable("MenuItemPromotions");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Customer_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Delivery_Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Order_Time")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentMethod_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("PaymentMethod_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Akla.SharedData.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MenuItem_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Order_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Special_Instructions")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Order_Id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Akla.SharedData.Models.PaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Method_Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Discount_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount_Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Customer_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Party_Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("Reservatoin_Time")
                        .HasColumnType("datetime2");

                    b.Property<long>("RestaurantTable_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Special_Requests")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("RestaurantTable_Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Akla.SharedData.Models.RestaurantTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LocationZone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RestaurantTables");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Customer_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("MenuItem_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("Review_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Customer_Id")
                        .IsUnique();

                    b.HasIndex("MenuItem_Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Address", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Akla.SharedData.Models.CustomerPhone", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Customer", "Customer")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Delivery", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Driver", "Driver")
                        .WithMany("Deliveries")
                        .HasForeignKey("Driver_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("Akla.SharedData.Models.Delivery", "Order_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Akla.SharedData.Models.DriverPhone", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Driver", "Driver")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("Driver_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Image", b =>
                {
                    b.HasOne("Akla.SharedData.Models.MenuItem", "MenuItem")
                        .WithMany("Images")
                        .HasForeignKey("MenuItem_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.Promotion", "Promotion")
                        .WithMany("Images")
                        .HasForeignKey("Promotion_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuCategoryItem", b =>
                {
                    b.HasOne("Akla.SharedData.Models.MenuCategory", "MenuCategory")
                        .WithMany("MenuCategoryItems")
                        .HasForeignKey("MenuCategory_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.MenuItem", "MenuItem")
                        .WithMany("MenuCategoryItems")
                        .HasForeignKey("MenuItem_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MenuCategory");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuItemPromotion", b =>
                {
                    b.HasOne("Akla.SharedData.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemPromotions")
                        .HasForeignKey("MenuItem_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.Promotion", "Promotion")
                        .WithMany("MenuItemPromotions")
                        .HasForeignKey("Promotion_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Order", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethod_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Akla.SharedData.Models.OrderItem", b =>
                {
                    b.HasOne("Akla.SharedData.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Reservation", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.RestaurantTable", "RestaurantTable")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantTable_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Review", b =>
                {
                    b.HasOne("Akla.SharedData.Models.Customer", "Customer")
                        .WithOne("Review")
                        .HasForeignKey("Akla.SharedData.Models.Review", "Customer_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Akla.SharedData.Models.MenuItem", "MenuItem")
                        .WithMany("Reviews")
                        .HasForeignKey("MenuItem_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("PhoneNumbers");

                    b.Navigation("Reservations");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Driver", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuCategory", b =>
                {
                    b.Navigation("MenuCategoryItems");
                });

            modelBuilder.Entity("Akla.SharedData.Models.MenuItem", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("MenuCategoryItems");

                    b.Navigation("MenuItemPromotions");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Akla.SharedData.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Akla.SharedData.Models.Promotion", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("MenuItemPromotions");
                });

            modelBuilder.Entity("Akla.SharedData.Models.RestaurantTable", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
